[project]
name = "scoreboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pyserial>=3.5",
    "pynput>=1.7",
    "ruff>=0.14.9",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]

[tool.pytest.ini_options]
pythonpath = ["."]
